import 'package:flutter/material.dart';
import 'care_store.dart';
import 'models.dart';
Future<void> main() async { WidgetsFlutterBinding.ensureInitialized(); runApp(FamilyCareApp(store:await CareStore.create())); }
class FamilyCareApp extends StatelessWidget { const FamilyCareApp({super.key,required this.store}); final CareStore store; @override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,theme:ThemeData(colorSchemeSeed:const Color(0xff006a63),useMaterial3:true),home:CareShell(store:store)); }
class CareShell extends StatefulWidget { const CareShell({super.key,required this.store}); final CareStore store; @override State<CareShell> createState()=>_CareShellState(); }
class _CareShellState extends State<CareShell> { int tab=0; final names=['Home','Family','Check-in','Tasks','Settings']; @override Widget build(BuildContext c)=>AnimatedBuilder(animation:widget.store,builder:(c,_)=>Scaffold(appBar:AppBar(title:Text(names[tab]),actions:[RolePicker(store:widget.store)]),body:SafeArea(child:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:520),child:page()))),bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(n)=>setState(()=>tab=n),destinations:const [NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'Home'),NavigationDestination(icon:Icon(Icons.people_outline),selectedIcon:Icon(Icons.people),label:'Family'),NavigationDestination(icon:Icon(Icons.check_circle_outline),selectedIcon:Icon(Icons.check_circle),label:'Check-in'),NavigationDestination(icon:Icon(Icons.task_outlined),selectedIcon:Icon(Icons.task),label:'Tasks'),NavigationDestination(icon:Icon(Icons.settings_outlined),selectedIcon:Icon(Icons.settings),label:'Settings')]))); Widget page()=>[Home(store:widget.store),Family(store:widget.store),CheckIn(store:widget.store),Tasks(store:widget.store),const Settings()][tab]; }
class RolePicker extends StatelessWidget { const RolePicker({super.key,required this.store}); final CareStore store; @override Widget build(BuildContext c)=>DropdownButton<Role>(value:store.activeRole,onChanged:(r){if(r!=null)store.setRole(r);},items:Role.values.map((r)=>DropdownMenuItem(value:r,child:Text(r.name))).toList()); }
class Home extends StatelessWidget { const Home({super.key,required this.store}); final CareStore store; @override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(16),children:[Text('Today needs attention',style:Theme.of(c).textTheme.headlineSmall),const SizedBox(height:8),...store.alerts.map((a)=>Card(color:a.highPriority?Theme.of(c).colorScheme.errorContainer:null,child:ListTile(leading:Icon(a.highPriority?Icons.priority_high:Icons.info_outline),title:Text(a.title),subtitle:Text(a.detail))))]); }
class Family extends StatelessWidget { const Family({super.key,required this.store}); final CareStore store; @override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(16),children:store.members.map((m)=>Card(child:ListTile(leading:CircleAvatar(child:Text(m.name[0])),title:Text(m.name),subtitle:Text(m.status),trailing:m.id=='mother'?Text(store.med.name):null))).toList()); }
class CheckIn extends StatelessWidget { const CheckIn({super.key,required this.store}); final CareStore store; @override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(16),children:[Text('Check in as ${store.activeRole.name}',style:Theme.of(c).textTheme.titleLarge),const SizedBox(height:12),button(c,'Safe today',CheckInType.safe),button(c,'Medication completed',CheckInType.medicationCompleted),button(c,'Need assistance',CheckInType.needAssistance),if(store.activeRole==Role.mother&&store.med==MedicationStatus.pending)FilledButton(onPressed:store.completeMedication,child:const Text('Mark medication completed'))]); Widget button(BuildContext c,String text,CheckInType type)=>Padding(padding:const EdgeInsets.only(bottom:10),child:FilledButton.tonal(onPressed:()=>store.checkIn(type),child:Text(text))); }
class Tasks extends StatelessWidget { const Tasks({super.key,required this.store}); final CareStore store; @override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(16),children:store.tasks.map((t)=>Card(child:ListTile(leading:Checkbox(value:t.complete,onChanged:(v)=>store.updateTask(t.copyWith(complete:v))),title:Text(t.title),subtitle:Text('Assigned to ${t.assigneeId}${t.needsHelp?' • Need help':''}'),trailing:PopupMenuButton<String>(onSelected:(id)=>store.updateTask(t.copyWith(assigneeId:id)),itemBuilder:(_)=>store.members.map((m)=>PopupMenuItem(value:m.id,child:Text('Assign to ${m.name}'))).toList())))).toList()); }
class Settings extends StatefulWidget { const Settings({super.key}); @override State<Settings> createState()=>_SettingsState(); } class _SettingsState extends State<Settings>{bool n=true,c=false;@override Widget build(BuildContext x)=>ListView(padding:const EdgeInsets.all(16),children:[SwitchListTile(title:const Text('Notifications'),subtitle:const Text('Mock permission'),value:n,onChanged:(v)=>setState(()=>n=v)),SwitchListTile(title:const Text('Calendar access'),subtitle:const Text('Mock permission'),value:c,onChanged:(v)=>setState(()=>c=v))]);}
